using Microsoft.CodeAnalysis.Testing;

namespace NextUnit.Generator.Tests;

/// <summary>
/// Tests for entry point generation in NextUnitGenerator.
/// </summary>
public class EntryPointGeneratorTests
{
    [Fact]
    public async Task NoExistingEntryPoint_GeneratesEntryPointAsync()
    {
        var source = @"
using NextUnit;

namespace TestProject;

public class TestClass
{
    [Test]
    public void SimpleTest()
    {
    }
}";

        var test = new CSharpSourceGeneratorVerifier<NextUnitGenerator>.Test
        {
            TestCode = source,
        };

        // Verify that Program.g.cs is generated
        var expectedEntryPoint = @"// <auto-generated />
#nullable enable
using System.Threading.Tasks;
using Microsoft.Testing.Platform.Builder;
using NextUnit.Platform;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static class Program
{
    private static async Task<int> Main(string[] args)
    {
        var builder = await TestApplication.CreateBuilderAsync(args);
        builder.AddNextUnit();
        using var app = await builder.BuildAsync();
        return await app.RunAsync();
    }
}";

        test.TestState.GeneratedSources.Add(
            (typeof(NextUnitGenerator), "Program.g.cs", expectedEntryPoint));

        // Skip the GeneratedTestRegistry.g.cs check to focus on entry point
        test.TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck;

        await test.RunAsync();
    }

    [Fact]
    public async Task ExistingEntryPoint_DoesNotGenerateEntryPointAsync()
    {
        var source = @"
using NextUnit;
using System.Threading.Tasks;

namespace TestProject;

public class TestClass
{
    [Test]
    public void SimpleTest()
    {
    }
}

public static class Program
{
    public static async Task<int> Main(string[] args)
    {
        return 0;
    }
}";

        var test = new CSharpSourceGeneratorVerifier<NextUnitGenerator>.Test
        {
            TestCode = source,
            // Skip verifying generated source files, we just want to verify no errors
            TestBehaviors = TestBehaviors.SkipGeneratedSourcesCheck,
        };

        // The test should pass without generating Program.g.cs
        // since an entry point already exists
        await test.RunAsync();
    }

    // Removed redundant test: GeneratedEntryPoint_CompilesSuccessfullyAsync
}
