<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SpeedComparison.Analysis\SpeedComparison.Analysis.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.6.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
        <PackageReference Include="ProcessX" Version="1.5.6" />
    </ItemGroup>

</Project>
