using System.ComponentModel;
using NextUnit.Shared;

namespace NextUnit.Internal;

/// <summary>
/// Provides direct access to source-generated test metadata.
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public interface IGeneratedTestRegistry
{
    /// <summary>Gets statically expanded test cases.</summary>
    public IReadOnlyList<TestCaseDescriptor> TestCases { get; }

    /// <summary>Gets descriptors backed by method-level test data.</summary>
    public IReadOnlyList<TestDataDescriptor> TestDataDescriptors { get; }

    /// <summary>Gets descriptors backed by class data sources.</summary>
    public IReadOnlyList<ClassDataSourceDescriptor> ClassDataSourceDescriptors { get; }

    /// <summary>Gets descriptors backed by combined parameter data sources.</summary>
    public IReadOnlyList<CombinedDataSourceDescriptor> CombinedDataSourceDescriptors { get; }

    /// <summary>Gets assembly setup methods.</summary>
    public LifecycleMethodDelegate[] GlobalBeforeAssemblyMethods { get; }

    /// <summary>Gets assembly teardown methods.</summary>
    public LifecycleMethodDelegate[] GlobalAfterAssemblyMethods { get; }

    /// <summary>Gets session setup methods.</summary>
    public LifecycleMethodDelegate[] GlobalBeforeSessionMethods { get; }

    /// <summary>Gets session teardown methods.</summary>
    public LifecycleMethodDelegate[] GlobalAfterSessionMethods { get; }

    /// <summary>
    /// Gets the compile-time test case cap this assembly was generated under, which discovery
    /// applies as its baseline.
    /// </summary>
    /// <remarks>
    /// Default-implemented rather than required: a registry generated by an earlier NextUnit is
    /// already compiled against the interface without this member, and a required one would make
    /// this release unable to read it at all. Such a registry answers the built-in default, which is
    /// the cap it was itself generated under unless its project set the property -- the one case
    /// this member exists to carry, and the one an old registry cannot report.
    /// </remarks>
    public int MaxTestCasesPerMethod => TestCaseExpansionPolicy.DefaultMaxTestCasesPerMethod;
}

/// <summary>
/// Connects generated test metadata to the in-process test host without runtime assembly loading.
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public static class GeneratedTestRegistryStore
{
    private static IGeneratedTestRegistry? _current;

    /// <summary>Gets the registry generated for the current test application.</summary>
    public static IGeneratedTestRegistry? Current => Volatile.Read(ref _current);

    /// <summary>Registers the metadata generated for the current test application.</summary>
    public static void Register(IGeneratedTestRegistry registry)
    {
        ArgumentNullException.ThrowIfNull(registry);
        Volatile.Write(ref _current, registry);
    }
}
