using Microsoft.Testing.Platform.Builder;

namespace NextUnit.Platform;

/// <summary>
/// Registers NextUnit with entry points generated by Microsoft.Testing.Platform.MSBuild.
/// </summary>
public static class TestingPlatformBuilderHook
{
    /// <summary>
    /// Adds the NextUnit test framework to a generated test application.
    /// </summary>
    /// <param name="builder">The test application builder.</param>
    /// <param name="args">The test application command-line arguments.</param>
    public static void AddExtensions(ITestApplicationBuilder builder, string[] args)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(args);

        builder.AddNextUnit();
    }
}
