using System.Collections.Immutable;
using System.Globalization;
using NextUnit.Generator.Builders;
using NextUnit.Generator.Helpers;
using NextUnit.Generator.Models;

namespace NextUnit.Generator.Emitters;

/// <summary>
/// Emits <c>GeneratedTestRegistry.g.cs</c>, the registry the test host reads at startup.
/// </summary>
/// <remarks>
/// The type name, the property names, and the module initializer are a public contract: the VSTest
/// adapter resolves <c>NextUnit.Generated.GeneratedTestRegistry</c> by string and reads these
/// properties by name. Renaming anything emitted here breaks discovery at runtime rather than at
/// compile time.
/// </remarks>
internal static class RegistryEmitter
{
    public static string Emit(
        IReadOnlyList<EmittableTestMethod> tests,
        ImmutableArray<LifecycleMethodDescriptor> beforeLifecycle,
        ImmutableArray<LifecycleMethodDescriptor> afterLifecycle,
        int maxTestCasesPerMethod)
    {
        var lifecycleMethods = beforeLifecycle.Concat(afterLifecycle).ToList();
        var lifecycleByType = lifecycleMethods
            .GroupBy(l => l.FullyQualifiedTypeName)
            .ToDictionary(g => g.Key, g => g.ToList());
        var globalLifecycle = GlobalLifecycleMethods.Collect(lifecycleMethods);
        var partition = TestPartition.Create(tests);

        var writer = new CodeWriter();
        EmitFileHeader(writer);
        writer.Indent();
        EmitEmptyArrayFields(writer);

        EmitDescriptorArrayProperty(writer, "TestCases", "global::NextUnit.Internal.TestCaseDescriptor", () =>
        {
            EmitRegularTestCases(writer, partition.RegularTests, lifecycleByType);
            EmitMatrixTestCases(writer, partition.MatrixTests, lifecycleByType);
        });

        EmitDescriptorArrayProperty(writer, "TestDataDescriptors", "global::NextUnit.Internal.TestDataDescriptor", () =>
        {
            foreach (var test in partition.TestDataTests)
            {
                var methods = LifecycleMethodsFor(lifecycleByType, test);
                foreach (var dataSource in test.TestDataSources)
                {
                    TestCaseEmitter.EmitTestDataDescriptor(writer, test, methods, dataSource);
                }
            }
        });

        EmitDescriptorArrayProperty(writer, "ClassDataSourceDescriptors", "global::NextUnit.Internal.ClassDataSourceDescriptor", () =>
        {
            foreach (var test in partition.ClassDataSourceTests)
            {
                TestCaseEmitter.EmitClassDataSourceDescriptor(
                    writer, test, LifecycleMethodsFor(lifecycleByType, test), test.ClassDataSources);
            }
        });

        EmitDescriptorArrayProperty(writer, "CombinedDataSourceDescriptors", "global::NextUnit.Internal.CombinedDataSourceDescriptor", () =>
        {
            foreach (var test in partition.CombinedDataSourceTests)
            {
                TestCaseEmitter.EmitCombinedDataSourceDescriptor(
                    writer, test, LifecycleMethodsFor(lifecycleByType, test));
            }
        });

        EmitGlobalLifecycleProperty(writer, "GlobalBeforeAssemblyMethods", globalLifecycle.BeforeAssembly);
        EmitGlobalLifecycleProperty(writer, "GlobalAfterAssemblyMethods", globalLifecycle.AfterAssembly);
        EmitGlobalLifecycleProperty(writer, "GlobalBeforeSessionMethods", globalLifecycle.BeforeSession);
        EmitGlobalLifecycleProperty(writer, "GlobalAfterSessionMethods", globalLifecycle.AfterSession);
        EmitMaxTestCasesPerMethod(writer, maxTestCasesPerMethod);

        EmitDynamicDependencies(writer, partition);
        EmitModuleInitializer(writer);
        EmitRegistryProvider(writer);

        writer.Unindent();
        writer.WriteLine("}");
        return writer.ToString();
    }

    private static void EmitFileHeader(CodeWriter writer)
    {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#pragma warning disable");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Threading;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine();
        writer.WriteLine("namespace NextUnit.Generated;");
        writer.WriteLine();
        writer.WriteLine("[global::System.CodeDom.Compiler.GeneratedCode(\"NextUnit.Generator\", \"1.0.0\")]");
        writer.WriteLine("internal static class GeneratedTestRegistry");
        writer.WriteLine("{");
    }

    // Shared empty arrays keep the generated file smaller and avoid repeating the type resolution
    // for every descriptor that has no lifecycle methods, categories, dependencies, or parameters.
    private static void EmitEmptyArrayFields(CodeWriter writer)
    {
        writer.WriteLine("private static readonly global::NextUnit.Internal.LifecycleMethodDelegate[] EmptyLifecycleMethods = [];");
        writer.WriteLine("private static readonly string[] EmptyStrings = [];");
        writer.WriteLine("private static readonly global::NextUnit.Internal.TestCaseId[] EmptyTestCaseIds = [];");
        writer.WriteLine("private static readonly global::NextUnit.Internal.DependencyInfo[] EmptyDependencyInfos = [];");
        writer.WriteLine("private static readonly global::System.Type[] EmptyTypes = [];");
        writer.WriteLine();
    }

    private static void EmitDescriptorArrayProperty(
        CodeWriter writer,
        string propertyName,
        string elementTypeName,
        Action emitElements)
    {
        writer.WriteLine($"public static global::System.Collections.Generic.IReadOnlyList<{elementTypeName}> {propertyName} {{ get; }} =");
        writer.Indent();
        writer.WriteLine($"new {elementTypeName}[]");
        writer.WriteLine("{");
        writer.Indent();
        emitElements();
        writer.Unindent();
        writer.WriteLine("};");
        writer.Unindent();
        writer.WriteLine();
    }

    private static void EmitRegularTestCases(
        CodeWriter writer,
        List<TestMethodDescriptor> tests,
        Dictionary<string, List<LifecycleMethodDescriptor>> lifecycleByType)
    {
        foreach (var test in tests)
        {
            var lifecycleMethods = LifecycleMethodsFor(lifecycleByType, test);
            var repeatCount = test.RepeatCount ?? 1;
            var hasRepeatAttribute = test.RepeatCount.HasValue;

            if (test.ArgumentSets.IsDefaultOrEmpty)
            {
                // No arguments - emit repeatCount test cases
                for (var repeatIndex = 0; repeatIndex < repeatCount; repeatIndex++)
                {
                    // Emit repeat index if [Repeat] attribute is present (even for Repeat(1))
                    var repeatIndexToEmit = hasRepeatAttribute ? repeatIndex : (int?)null;
                    TestCaseEmitter.EmitTestCase(writer, test, lifecycleMethods, null, -1, repeatIndexToEmit);
                }

                continue;
            }

            // With arguments - emit argumentSets.Length * repeatCount test cases
            for (var argIndex = 0; argIndex < test.ArgumentSets.Length; argIndex++)
            {
                for (var repeatIndex = 0; repeatIndex < repeatCount; repeatIndex++)
                {
                    var repeatIndexToEmit = hasRepeatAttribute ? repeatIndex : (int?)null;
                    TestCaseEmitter.EmitTestCase(writer, test, lifecycleMethods, test.ArgumentSets[argIndex], argIndex, repeatIndexToEmit);
                }
            }
        }
    }

    /// <remarks>
    /// The combinations are the ones <c>TestCaseExpansionValidator</c> already built and filtered to
    /// count what this loop emits, not a second expansion: <c>MatrixHelper.ApplyExclusions</c> is
    /// exclusions x combinations x parameter width and nothing bounds the exclusion count, so a
    /// method at the cap with thousands of <c>[MatrixExclusion]</c> attributes used to pay that pass
    /// twice for one answer. Reading the value the count came from is also what keeps the two from
    /// disagreeing about which combinations an exclusion removes.
    /// </remarks>
    private static void EmitMatrixTestCases(
        CodeWriter writer,
        List<EmittableTestMethod> tests,
        Dictionary<string, List<LifecycleMethodDescriptor>> lifecycleByType)
    {
        foreach (var emittable in tests)
        {
            var test = emittable.Test;
            var lifecycleMethods = LifecycleMethodsFor(lifecycleByType, test);
            var repeatCount = test.RepeatCount ?? 1;
            var hasRepeatAttribute = test.RepeatCount.HasValue;
            var combinations = emittable.MatrixCombinations;

            for (var matrixIndex = 0; matrixIndex < combinations.Length; matrixIndex++)
            {
                for (var repeatIndex = 0; repeatIndex < repeatCount; repeatIndex++)
                {
                    var repeatIndexToEmit = hasRepeatAttribute ? repeatIndex : (int?)null;
                    TestCaseEmitter.EmitMatrixTestCase(writer, test, lifecycleMethods, combinations[matrixIndex], matrixIndex, repeatIndexToEmit);
                }
            }
        }
    }

    private static void EmitGlobalLifecycleProperty(
        CodeWriter writer,
        string propertyName,
        List<LifecycleMethodDescriptor> methods)
    {
        writer.Write($"public static global::NextUnit.Internal.LifecycleMethodDelegate[] {propertyName} {{ get; }} = ");

        // An unreachable hook is dropped rather than emitted: NEXTUNIT015 already fails the build,
        // and emitting the call would add a CS0122 in a file the user did not write.
        methods = methods.Where(method => method.IsReachable).ToList();

        if (methods.Count == 0)
        {
            writer.WriteLine("EmptyLifecycleMethods;");
        }
        else
        {
            writer.WriteLine("new global::NextUnit.Internal.LifecycleMethodDelegate[]");
            writer.WriteLine("{");
            writer.Indent();
            foreach (var method in methods)
            {
                writer.WriteLine($"{CodeBuilder.BuildLifecycleMethodDelegate(method.InvocationTypeName, method.MethodName, method.IsStatic, method.ReturnKind, method.AcceptsCancellationToken)},");
            }

            writer.Unindent();
            writer.WriteLine("};");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// Emits the compile-time cap this registry was generated under, so discovery bounds the same
    /// method by the same number.
    /// </summary>
    /// <remarks>
    /// Emitted for every registry rather than only when the project set the property. Absence would
    /// have to mean "the default", which is the ambiguity this member exists to remove: discovery
    /// could not then tell a project that never configured a cap from one whose registry predates
    /// the member, and only the second may be read as the built-in default.
    /// </remarks>
    private static void EmitMaxTestCasesPerMethod(CodeWriter writer, int maxTestCasesPerMethod)
    {
        writer.WriteLine($"public static int MaxTestCasesPerMethod {{ get; }} = {maxTestCasesPerMethod.ToString(CultureInfo.InvariantCulture)};");
        writer.WriteLine();
    }

    /// <summary>
    /// Roots every type the registry reaches only through reflection, or trimming and AOT publishing
    /// drop it.
    /// </summary>
    /// <remarks>
    /// The data source roots are read out of the partition rather than off the raw descriptors,
    /// because the partition is what decides which sources are emitted at all. A method-level
    /// <c>[ClassDataSource&lt;T&gt;]</c> or <c>[TestData]</c> on a method that also carries a
    /// parameter-level source lands in <c>CombinedDataSourceTests</c>, so no descriptor and no
    /// <c>new T()</c> factory is written for it and no row ever comes from it; rooting it anyway held
    /// every member of a dead type against the trimmer. Dropping the root is also what lets
    /// <c>NU0022</c> stop reporting a shadowed source: that root was the last thing naming <c>T</c>,
    /// and the <c>CS0122</c> it produced on a private or protected nested source is the error the
    /// rule exists to replace. The two moves are one change -- gating the rule while the root stayed
    /// was tried in PR #234 and reverted, because it left the consumer with the bare compiler error.
    /// The test class and the display name formatter are rooted for every test in every bucket, since
    /// both are emitted whichever descriptor the test becomes.
    /// </remarks>
    private static void EmitDynamicDependencies(CodeWriter writer, TestPartition partition)
    {
        var expandedSourceTypes = partition.TestDataTests
            .SelectMany(test => test.TestDataSources.Select(source => source.MemberTypeName))
            .Concat(partition.ClassDataSourceTests
                .SelectMany(test => test.ClassDataSources.Select(source => source.TypeName)))
            .Concat(partition.CombinedDataSourceTests
                .SelectMany(test => test.CombinedParameterSources
                    .SelectMany(source => new[] { source.MemberTypeName, source.ClassTypeName })));

        var reflectionRootTypes = partition.AllTests
            .SelectMany(test => new[]
            {
                test.FullyQualifiedTypeName,
                test.DisplayNameFormatterType
            })
            .Concat(expandedSourceTypes)
            .Where(typeName => !string.IsNullOrWhiteSpace(typeName))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(typeName => typeName, StringComparer.Ordinal);

        foreach (var typeName in reflectionRootTypes)
        {
            writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.DynamicDependency(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof({typeName}))]");
        }
    }

    private static void EmitModuleInitializer(CodeWriter writer)
    {
        writer.WriteLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
        writer.WriteLine("internal static void RegisterWithTestHost()");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("global::NextUnit.Internal.GeneratedTestRegistryStore.Register(new RegistryProvider());");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void EmitRegistryProvider(CodeWriter writer)
    {
        writer.WriteLine("private sealed class RegistryProvider : global::NextUnit.Internal.IGeneratedTestRegistry");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("public global::System.Collections.Generic.IReadOnlyList<global::NextUnit.Internal.TestCaseDescriptor> TestCases => GeneratedTestRegistry.TestCases;");
        writer.WriteLine("public global::System.Collections.Generic.IReadOnlyList<global::NextUnit.Internal.TestDataDescriptor> TestDataDescriptors => GeneratedTestRegistry.TestDataDescriptors;");
        writer.WriteLine("public global::System.Collections.Generic.IReadOnlyList<global::NextUnit.Internal.ClassDataSourceDescriptor> ClassDataSourceDescriptors => GeneratedTestRegistry.ClassDataSourceDescriptors;");
        writer.WriteLine("public global::System.Collections.Generic.IReadOnlyList<global::NextUnit.Internal.CombinedDataSourceDescriptor> CombinedDataSourceDescriptors => GeneratedTestRegistry.CombinedDataSourceDescriptors;");
        writer.WriteLine("public global::NextUnit.Internal.LifecycleMethodDelegate[] GlobalBeforeAssemblyMethods => GeneratedTestRegistry.GlobalBeforeAssemblyMethods;");
        writer.WriteLine("public global::NextUnit.Internal.LifecycleMethodDelegate[] GlobalAfterAssemblyMethods => GeneratedTestRegistry.GlobalAfterAssemblyMethods;");
        writer.WriteLine("public global::NextUnit.Internal.LifecycleMethodDelegate[] GlobalBeforeSessionMethods => GeneratedTestRegistry.GlobalBeforeSessionMethods;");
        writer.WriteLine("public global::NextUnit.Internal.LifecycleMethodDelegate[] GlobalAfterSessionMethods => GeneratedTestRegistry.GlobalAfterSessionMethods;");
        writer.WriteLine("public int MaxTestCasesPerMethod => GeneratedTestRegistry.MaxTestCasesPerMethod;");
        writer.Unindent();
        writer.WriteLine("}");
    }

    /// <summary>
    /// The hooks that apply to one test, base classes first.
    /// </summary>
    /// <remarks>
    /// The inherited hooks come from the descriptor, which walked the base chain with symbols in
    /// hand, and the test class own hooks from the two syntax providers, which is where they have
    /// always come from. Joining the base levels here against the providers instead was rejected:
    /// the providers see only this compilation, so a base class in a referenced assembly would keep
    /// contributing nothing, silently, which is the failure this change exists to remove.
    /// </remarks>
    private static TestLifecycleMethods LifecycleMethodsFor(
        Dictionary<string, List<LifecycleMethodDescriptor>> lifecycleByType,
        TestMethodDescriptor test)
    {
        var declared = lifecycleByType.TryGetValue(test.FullyQualifiedTypeName, out var methods)
            ? methods
            : new List<LifecycleMethodDescriptor>();

        return TestLifecycleMethods.Create(test.InheritedLifecycleMethods, declared);
    }

    /// <summary>
    /// Splits the discovered tests by which registry property they belong to.
    /// </summary>
    /// <remarks>
    /// A test carrying several data-source kinds lands in exactly one bucket, and the generator
    /// reports the conflict as a diagnostic separately. The precedence lives in
    /// <see cref="TestExpansionClassifier"/> rather than here, because the expansion validator
    /// charges the cap by the same decision and computes the matrix bucket's combinations for it.
    /// </remarks>
    private sealed class TestPartition
    {
        public List<TestMethodDescriptor> RegularTests { get; } = new();
        public List<EmittableTestMethod> MatrixTests { get; } = new();
        public List<TestMethodDescriptor> TestDataTests { get; } = new();
        public List<TestMethodDescriptor> ClassDataSourceTests { get; } = new();
        public List<TestMethodDescriptor> CombinedDataSourceTests { get; } = new();

        public IEnumerable<TestMethodDescriptor> AllTests =>
            RegularTests
                .Concat(MatrixTests.Select(static matrix => matrix.Test))
                .Concat(TestDataTests)
                .Concat(ClassDataSourceTests)
                .Concat(CombinedDataSourceTests);

        public static TestPartition Create(IReadOnlyList<EmittableTestMethod> tests)
        {
            var partition = new TestPartition();

            foreach (var emittable in tests)
            {
                var test = emittable.Test;

                switch (TestExpansionClassifier.Classify(test))
                {
                    case TestExpansionKind.CombinedDataSource:
                        partition.CombinedDataSourceTests.Add(test);
                        break;

                    case TestExpansionKind.ClassDataSource:
                        partition.ClassDataSourceTests.Add(test);
                        break;

                    case TestExpansionKind.TestData:
                        partition.TestDataTests.Add(test);
                        break;

                    case TestExpansionKind.Matrix:
                        partition.MatrixTests.Add(emittable);
                        break;

                    default:
                        partition.RegularTests.Add(test);
                        break;
                }
            }

            return partition;
        }
    }

    /// <summary>
    /// The Assembly and Session scoped lifecycle methods, which the registry exposes once for the
    /// whole assembly rather than per descriptor.
    /// </summary>
    private sealed class GlobalLifecycleMethods
    {
        public List<LifecycleMethodDescriptor> BeforeAssembly { get; } = new();
        public List<LifecycleMethodDescriptor> AfterAssembly { get; } = new();
        public List<LifecycleMethodDescriptor> BeforeSession { get; } = new();
        public List<LifecycleMethodDescriptor> AfterSession { get; } = new();

        public static GlobalLifecycleMethods Collect(List<LifecycleMethodDescriptor> lifecycleMethods)
        {
            var global = new GlobalLifecycleMethods();

            foreach (var method in lifecycleMethods)
            {
                // Instance methods are skipped: an Assembly or Session scoped hook would have to
                // run against an arbitrarily chosen instance, which has no defensible semantics.
                if (!method.IsStatic)
                {
                    continue;
                }

                if (method.BeforeScopes.Contains(LifecycleScopeConstants.Assembly))
                {
                    global.BeforeAssembly.Add(method);
                }

                if (method.AfterScopes.Contains(LifecycleScopeConstants.Assembly))
                {
                    global.AfterAssembly.Add(method);
                }

                if (method.BeforeScopes.Contains(LifecycleScopeConstants.Session))
                {
                    global.BeforeSession.Add(method);
                }

                if (method.AfterScopes.Contains(LifecycleScopeConstants.Session))
                {
                    global.AfterSession.Add(method);
                }
            }

            return global;
        }
    }
}
