using System.Collections.Immutable;
using NextUnit.Generator.Builders;
using NextUnit.Generator.Helpers;
using NextUnit.Generator.Models;

namespace NextUnit.Generator.Emitters;

/// <summary>
/// Emits <c>GeneratedTestRegistry.g.cs</c>, the registry the test host reads at startup.
/// </summary>
/// <remarks>
/// The type name, the property names, and the module initializer are a public contract: the VSTest
/// adapter resolves <c>NextUnit.Generated.GeneratedTestRegistry</c> by string and reads these
/// properties by name. Renaming anything emitted here breaks discovery at runtime rather than at
/// compile time.
/// </remarks>
internal static class RegistryEmitter
{
    public static string Emit(
        IReadOnlyList<TestMethodDescriptor> tests,
        ImmutableArray<LifecycleMethodDescriptor> beforeLifecycle,
        ImmutableArray<LifecycleMethodDescriptor> afterLifecycle)
    {
        var lifecycleMethods = beforeLifecycle.Concat(afterLifecycle).ToList();
        var lifecycleByType = lifecycleMethods
            .GroupBy(l => l.FullyQualifiedTypeName)
            .ToDictionary(g => g.Key, g => g.ToList());
        var globalLifecycle = GlobalLifecycleMethods.Collect(lifecycleMethods);
        var partition = TestPartition.Create(tests);

        var writer = new CodeWriter();
        EmitFileHeader(writer);
        writer.Indent();
        EmitEmptyArrayFields(writer);

        EmitDescriptorArrayProperty(writer, "TestCases", "global::NextUnit.Internal.TestCaseDescriptor", () =>
        {
            EmitRegularTestCases(writer, partition.RegularTests, lifecycleByType);
            EmitMatrixTestCases(writer, partition.MatrixTests, lifecycleByType);
        });

        EmitDescriptorArrayProperty(writer, "TestDataDescriptors", "global::NextUnit.Internal.TestDataDescriptor", () =>
        {
            foreach (var test in partition.TestDataTests)
            {
                var methods = LifecycleMethodsFor(lifecycleByType, test);
                foreach (var dataSource in test.TestDataSources)
                {
                    TestCaseEmitter.EmitTestDataDescriptor(writer, test, methods, dataSource);
                }
            }
        });

        EmitDescriptorArrayProperty(writer, "ClassDataSourceDescriptors", "global::NextUnit.Internal.ClassDataSourceDescriptor", () =>
        {
            foreach (var test in partition.ClassDataSourceTests)
            {
                TestCaseEmitter.EmitClassDataSourceDescriptor(
                    writer, test, LifecycleMethodsFor(lifecycleByType, test), test.ClassDataSources);
            }
        });

        EmitDescriptorArrayProperty(writer, "CombinedDataSourceDescriptors", "global::NextUnit.Internal.CombinedDataSourceDescriptor", () =>
        {
            foreach (var test in partition.CombinedDataSourceTests)
            {
                TestCaseEmitter.EmitCombinedDataSourceDescriptor(
                    writer, test, LifecycleMethodsFor(lifecycleByType, test));
            }
        });

        EmitGlobalLifecycleProperty(writer, "GlobalBeforeAssemblyMethods", globalLifecycle.BeforeAssembly);
        EmitGlobalLifecycleProperty(writer, "GlobalAfterAssemblyMethods", globalLifecycle.AfterAssembly);
        EmitGlobalLifecycleProperty(writer, "GlobalBeforeSessionMethods", globalLifecycle.BeforeSession);
        EmitGlobalLifecycleProperty(writer, "GlobalAfterSessionMethods", globalLifecycle.AfterSession);

        EmitDynamicDependencies(writer, tests);
        EmitModuleInitializer(writer);
        EmitRegistryProvider(writer);

        writer.Unindent();
        writer.WriteLine("}");
        return writer.ToString();
    }

    private static void EmitFileHeader(CodeWriter writer)
    {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#pragma warning disable");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Threading;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine();
        writer.WriteLine("namespace NextUnit.Generated;");
        writer.WriteLine();
        writer.WriteLine("[global::System.CodeDom.Compiler.GeneratedCode(\"NextUnit.Generator\", \"1.0.0\")]");
        writer.WriteLine("internal static class GeneratedTestRegistry");
        writer.WriteLine("{");
    }

    // Shared empty arrays keep the generated file smaller and avoid repeating the type resolution
    // for every descriptor that has no lifecycle methods, categories, dependencies, or parameters.
    private static void EmitEmptyArrayFields(CodeWriter writer)
    {
        writer.WriteLine("private static readonly global::NextUnit.Internal.LifecycleMethodDelegate[] EmptyLifecycleMethods = [];");
        writer.WriteLine("private static readonly string[] EmptyStrings = [];");
        writer.WriteLine("private static readonly global::NextUnit.Internal.TestCaseId[] EmptyTestCaseIds = [];");
        writer.WriteLine("private static readonly global::NextUnit.Internal.DependencyInfo[] EmptyDependencyInfos = [];");
        writer.WriteLine("private static readonly global::System.Type[] EmptyTypes = [];");
        writer.WriteLine();
    }

    private static void EmitDescriptorArrayProperty(
        CodeWriter writer,
        string propertyName,
        string elementTypeName,
        Action emitElements)
    {
        writer.WriteLine($"public static global::System.Collections.Generic.IReadOnlyList<{elementTypeName}> {propertyName} {{ get; }} =");
        writer.Indent();
        writer.WriteLine($"new {elementTypeName}[]");
        writer.WriteLine("{");
        writer.Indent();
        emitElements();
        writer.Unindent();
        writer.WriteLine("};");
        writer.Unindent();
        writer.WriteLine();
    }

    private static void EmitRegularTestCases(
        CodeWriter writer,
        List<TestMethodDescriptor> tests,
        Dictionary<string, List<LifecycleMethodDescriptor>> lifecycleByType)
    {
        foreach (var test in tests)
        {
            var lifecycleMethods = LifecycleMethodsFor(lifecycleByType, test);
            var repeatCount = test.RepeatCount ?? 1;
            var hasRepeatAttribute = test.RepeatCount.HasValue;

            if (test.ArgumentSets.IsDefaultOrEmpty)
            {
                // No arguments - emit repeatCount test cases
                for (var repeatIndex = 0; repeatIndex < repeatCount; repeatIndex++)
                {
                    // Emit repeat index if [Repeat] attribute is present (even for Repeat(1))
                    var repeatIndexToEmit = hasRepeatAttribute ? repeatIndex : (int?)null;
                    TestCaseEmitter.EmitTestCase(writer, test, lifecycleMethods, null, -1, repeatIndexToEmit);
                }

                continue;
            }

            // With arguments - emit argumentSets.Length * repeatCount test cases
            for (var argIndex = 0; argIndex < test.ArgumentSets.Length; argIndex++)
            {
                for (var repeatIndex = 0; repeatIndex < repeatCount; repeatIndex++)
                {
                    var repeatIndexToEmit = hasRepeatAttribute ? repeatIndex : (int?)null;
                    TestCaseEmitter.EmitTestCase(writer, test, lifecycleMethods, test.ArgumentSets[argIndex], argIndex, repeatIndexToEmit);
                }
            }
        }
    }

    private static void EmitMatrixTestCases(
        CodeWriter writer,
        List<TestMethodDescriptor> tests,
        Dictionary<string, List<LifecycleMethodDescriptor>> lifecycleByType)
    {
        foreach (var test in tests)
        {
            var lifecycleMethods = LifecycleMethodsFor(lifecycleByType, test);
            var repeatCount = test.RepeatCount ?? 1;
            var hasRepeatAttribute = test.RepeatCount.HasValue;

            var combinations = MatrixHelper.ComputeCartesianProduct(test.MatrixParameters);
            combinations = MatrixHelper.ApplyExclusions(combinations, test.MatrixExclusions);

            for (var matrixIndex = 0; matrixIndex < combinations.Length; matrixIndex++)
            {
                for (var repeatIndex = 0; repeatIndex < repeatCount; repeatIndex++)
                {
                    var repeatIndexToEmit = hasRepeatAttribute ? repeatIndex : (int?)null;
                    TestCaseEmitter.EmitMatrixTestCase(writer, test, lifecycleMethods, combinations[matrixIndex], matrixIndex, repeatIndexToEmit);
                }
            }
        }
    }

    private static void EmitGlobalLifecycleProperty(
        CodeWriter writer,
        string propertyName,
        List<LifecycleMethodDescriptor> methods)
    {
        writer.Write($"public static global::NextUnit.Internal.LifecycleMethodDelegate[] {propertyName} {{ get; }} = ");

        // An unreachable hook is dropped rather than emitted: NEXTUNIT015 already fails the build,
        // and emitting the call would add a CS0122 in a file the user did not write.
        methods = methods.Where(method => method.IsReachable).ToList();

        if (methods.Count == 0)
        {
            writer.WriteLine("EmptyLifecycleMethods;");
        }
        else
        {
            writer.WriteLine("new global::NextUnit.Internal.LifecycleMethodDelegate[]");
            writer.WriteLine("{");
            writer.Indent();
            foreach (var method in methods)
            {
                writer.WriteLine($"{CodeBuilder.BuildLifecycleMethodDelegate(method.InvocationTypeName, method.MethodName, method.IsStatic, method.ReturnKind, method.AcceptsCancellationToken)},");
            }

            writer.Unindent();
            writer.WriteLine("};");
        }

        writer.WriteLine();
    }

    // Every type the registry reaches only through reflection needs a root, or trimming and AOT
    // publishing drop it.
    private static void EmitDynamicDependencies(CodeWriter writer, IReadOnlyList<TestMethodDescriptor> tests)
    {
        var reflectionRootTypes = tests
            .SelectMany(test => new[]
            {
                test.FullyQualifiedTypeName,
                test.DisplayNameFormatterType
            }
            .Concat(test.TestDataSources.Select(source => source.MemberTypeName))
            .Concat(test.ClassDataSources.Select(source => source.TypeName))
            .Concat(test.CombinedParameterSources.SelectMany(source => new[] { source.MemberTypeName, source.ClassTypeName })))
            .Where(typeName => !string.IsNullOrWhiteSpace(typeName))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(typeName => typeName, StringComparer.Ordinal);

        foreach (var typeName in reflectionRootTypes)
        {
            writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.DynamicDependency(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof({typeName}))]");
        }
    }

    private static void EmitModuleInitializer(CodeWriter writer)
    {
        writer.WriteLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
        writer.WriteLine("internal static void RegisterWithTestHost()");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("global::NextUnit.Internal.GeneratedTestRegistryStore.Register(new RegistryProvider());");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void EmitRegistryProvider(CodeWriter writer)
    {
        writer.WriteLine("private sealed class RegistryProvider : global::NextUnit.Internal.IGeneratedTestRegistry");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("public global::System.Collections.Generic.IReadOnlyList<global::NextUnit.Internal.TestCaseDescriptor> TestCases => GeneratedTestRegistry.TestCases;");
        writer.WriteLine("public global::System.Collections.Generic.IReadOnlyList<global::NextUnit.Internal.TestDataDescriptor> TestDataDescriptors => GeneratedTestRegistry.TestDataDescriptors;");
        writer.WriteLine("public global::System.Collections.Generic.IReadOnlyList<global::NextUnit.Internal.ClassDataSourceDescriptor> ClassDataSourceDescriptors => GeneratedTestRegistry.ClassDataSourceDescriptors;");
        writer.WriteLine("public global::System.Collections.Generic.IReadOnlyList<global::NextUnit.Internal.CombinedDataSourceDescriptor> CombinedDataSourceDescriptors => GeneratedTestRegistry.CombinedDataSourceDescriptors;");
        writer.WriteLine("public global::NextUnit.Internal.LifecycleMethodDelegate[] GlobalBeforeAssemblyMethods => GeneratedTestRegistry.GlobalBeforeAssemblyMethods;");
        writer.WriteLine("public global::NextUnit.Internal.LifecycleMethodDelegate[] GlobalAfterAssemblyMethods => GeneratedTestRegistry.GlobalAfterAssemblyMethods;");
        writer.WriteLine("public global::NextUnit.Internal.LifecycleMethodDelegate[] GlobalBeforeSessionMethods => GeneratedTestRegistry.GlobalBeforeSessionMethods;");
        writer.WriteLine("public global::NextUnit.Internal.LifecycleMethodDelegate[] GlobalAfterSessionMethods => GeneratedTestRegistry.GlobalAfterSessionMethods;");
        writer.Unindent();
        writer.WriteLine("}");
    }

    /// <summary>
    /// The hooks that apply to one test, base classes first.
    /// </summary>
    /// <remarks>
    /// The inherited hooks come from the descriptor, which walked the base chain with symbols in
    /// hand, and the test class own hooks from the two syntax providers, which is where they have
    /// always come from. Joining the base levels here against the providers instead was rejected:
    /// the providers see only this compilation, so a base class in a referenced assembly would keep
    /// contributing nothing, silently, which is the failure this change exists to remove.
    /// </remarks>
    private static TestLifecycleMethods LifecycleMethodsFor(
        Dictionary<string, List<LifecycleMethodDescriptor>> lifecycleByType,
        TestMethodDescriptor test)
    {
        var declared = lifecycleByType.TryGetValue(test.FullyQualifiedTypeName, out var methods)
            ? methods
            : new List<LifecycleMethodDescriptor>();

        return TestLifecycleMethods.Create(test.InheritedLifecycleMethods, declared);
    }

    /// <summary>
    /// Splits the discovered tests by which registry property they belong to.
    /// </summary>
    /// <remarks>
    /// The order of the checks is the precedence rule: a test carrying several data-source kinds
    /// lands in exactly one bucket, and the generator reports the conflict as a diagnostic
    /// separately.
    /// </remarks>
    private sealed class TestPartition
    {
        public List<TestMethodDescriptor> RegularTests { get; } = new();
        public List<TestMethodDescriptor> MatrixTests { get; } = new();
        public List<TestMethodDescriptor> TestDataTests { get; } = new();
        public List<TestMethodDescriptor> ClassDataSourceTests { get; } = new();
        public List<TestMethodDescriptor> CombinedDataSourceTests { get; } = new();

        public static TestPartition Create(IReadOnlyList<TestMethodDescriptor> tests)
        {
            var partition = new TestPartition();

            foreach (var test in tests)
            {
                if (!test.CombinedParameterSources.IsDefaultOrEmpty)
                {
                    partition.CombinedDataSourceTests.Add(test);
                }
                else if (!test.ClassDataSources.IsDefaultOrEmpty)
                {
                    partition.ClassDataSourceTests.Add(test);
                }
                else if (!test.TestDataSources.IsDefaultOrEmpty)
                {
                    partition.TestDataTests.Add(test);
                }
                else if (!test.MatrixParameters.IsDefaultOrEmpty)
                {
                    partition.MatrixTests.Add(test);
                }
                else
                {
                    partition.RegularTests.Add(test);
                }
            }

            return partition;
        }
    }

    /// <summary>
    /// The Assembly and Session scoped lifecycle methods, which the registry exposes once for the
    /// whole assembly rather than per descriptor.
    /// </summary>
    private sealed class GlobalLifecycleMethods
    {
        public List<LifecycleMethodDescriptor> BeforeAssembly { get; } = new();
        public List<LifecycleMethodDescriptor> AfterAssembly { get; } = new();
        public List<LifecycleMethodDescriptor> BeforeSession { get; } = new();
        public List<LifecycleMethodDescriptor> AfterSession { get; } = new();

        public static GlobalLifecycleMethods Collect(List<LifecycleMethodDescriptor> lifecycleMethods)
        {
            var global = new GlobalLifecycleMethods();

            foreach (var method in lifecycleMethods)
            {
                // Instance methods are skipped: an Assembly or Session scoped hook would have to
                // run against an arbitrarily chosen instance, which has no defensible semantics.
                if (!method.IsStatic)
                {
                    continue;
                }

                if (method.BeforeScopes.Contains(LifecycleScopeConstants.Assembly))
                {
                    global.BeforeAssembly.Add(method);
                }

                if (method.AfterScopes.Contains(LifecycleScopeConstants.Assembly))
                {
                    global.AfterAssembly.Add(method);
                }

                if (method.BeforeScopes.Contains(LifecycleScopeConstants.Session))
                {
                    global.BeforeSession.Add(method);
                }

                if (method.AfterScopes.Contains(LifecycleScopeConstants.Session))
                {
                    global.AfterSession.Add(method);
                }
            }

            return global;
        }
    }
}
